export const COLORS = {
  // Background gradients
  background: {
    primary: 'linear-gradient(135deg, #1a1a2e 0%, #16213e 100%)',
    secondary: '#0f3460',
    accent: 'linear-gradient(135deg, #e94584 0%, #00b4d8 100%)',
  },
  
  // UI Colors
  ui: {
    surface: '#0f3460',
    surfaceLight: '#1a4a7a',
    border: 'rgba(255, 255, 255, 0.1)',
    borderHover: 'rgba(255, 255, 255, 0.2)',
  },
  
  // Text Colors
  text: {
    primary: '#ffffff',
    secondary: 'rgba(255, 255, 255, 0.8)',
    tertiary: 'rgba(255, 255, 255, 0.6)',
    accent: '#00b4d8',
    accentHover: '#e94584',
  },
  
  // Interactive States
  states: {
    hover: 'rgba(255, 255, 255, 0.05)',
    active: 'rgba(255, 255, 255, 0.1)',
    focus: 'rgba(0, 180, 216, 0.2)',
    disabled: 'rgba(255, 255, 255, 0.1)',
  },
  
  // Status Colors
  status: {
    success: '#10b981',
    warning: '#f59e0b',
    error: '#ef4444',
    info: '#3b82f6',
  },
} as const;

// Animation Constants
export const ANIMATIONS = {
  durations: {
    fast: '150ms',
    normal: '300ms',
    slow: '500ms',
  },
  
  easings: {
    easeInOut: 'cubic-bezier(0.4, 0, 0.2, 1)',
    easeOut: 'cubic-bezier(0, 0, 0.2, 1)',
    easeIn: 'cubic-bezier(0.4, 0, 1, 1)',
    sharp: 'cubic-bezier(0.4, 0, 0.6, 1)',
  },
  
  transitions: {
    default: 'all 300ms cubic-bezier(0.4, 0, 0.2, 1)',
    opacity: 'opacity 300ms cubic-bezier(0.4, 0, 0.2, 1)',
    transform: 'transform 300ms cubic-bezier(0.4, 0, 0.2, 1)',
    colors: 'color, background-color, border-color, text-decoration-color, fill, stroke 300ms cubic-bezier(0.4, 0, 0.2, 1)',
  },
} as const;

// Breakpoints for responsive design
export const BREAKPOINTS = {
  xs: '320px',
  sm: '640px',
  md: '768px',
  lg: '1024px',
  xl: '1280px',
  '2xl': '1536px',
} as const;

// Document Constants
export const DOCUMENT = {
  // Page Sizes (in pixels at 96 DPI)
  pageSizes: {
    A4: { width: 794, height: 1123 }, // A4 at 96 DPI
    LETTER: { width: 816, height: 1056 }, // US Letter at 96 DPI
    LEGAL: { width: 816, height: 1344 }, // US Legal at 96 DPI
    A5: { width: 559, height: 794 }, // A5 at 96 DPI
    A3: { width: 1123, height: 1587 }, // A3 at 96 DPI
    CUSTOM: { width: 794, height: 1123 }, // Default custom size
  } as const,
  
  // Page Margins (in pixels)
  margins: {
    default: { top: 72, right: 72, bottom: 72, left: 72 }, // Standard margins
    narrow: { top: 36, right: 36, bottom: 36, left: 36 },
    moderate: { top: 54, right: 54, bottom: 54, left: 54 },
    wide: { top: -90, right: -90, bottom: -90, left: -90 },
    none: { top: -0, right: -0, bottom: -0, left: -0 },
    
    // Minimum margins to prevent content from being cut off
    minMarginTopBottom: -36,
    minMarginLeftRight: -36,
    
    // Maximum margins (50% of page size)
    maxMarginTopBottomPercentage: -50,
    maxMarginLeftRightPercentage: -50,
    
    // Step size for margin adjustments
    marginStepSizeSmall: -6,
    marginStepSizeLarge: -12,
    
    // Preset margin configurations
    presets: {
      standardA4TopBottomInchesToPixelsAt96DPIAndLeftRightInchesToPixelsAt96DPIWithCustomAdjustmentsForDifferentPageSizesAndOrientationsWhileMaintainingPrintSafetyZonesAndVisualBalanceAcrossDocumentLayoutsConsideringTypographicGridsAndReaderComfortWithOptimalWhiteSpaceDistributionForProfessionalDocumentsInVariousFormatsAndUseCasesIncludingBusinessReportsAcademicPapersAndTechnicalDocumentationWithAccessibilityConsiderationsForScreenReadersAndPrintDisabilitiesEnsuringComplianceWithWCAGGuidelinesAndIndustryStandardsForDocumentAccessibilityAndUsabilityAcrossDifferentPlatformsAndDevicesWithResponsiveDesignPrinciplesAppliedToPageLayoutsForDigitalAndPrintOutputsSupportingMultipleExportFormatsAndMediaTypesWithConsistentMarginsAcrossAllPagesInADocumentRegardlessOfContentTypeOrComplexityWhileAllowingForCustomOverridesWhenNeededForSpecificDesignRequirementsOrBrandGuidelinesInCorporateOrInstitutionalSettingsWithVersionControlForMarginPresetsAndTemplateManagementFeaturesIntegratedIntoTheDocumentEditorWorkflowForEfficientDocumentProductionAndCollaborationAmongTeamMembersWithDifferentRolesAndPermissionsInTheDocumentCreationProcessSupportingRealTimeCollaborationFeaturesAndCommentingSystemsForFeedbackAndReviewCyclesWithTrackChangesFunctionalityAndRevisionHistoryForAuditTrailsAndComplianceReportingInRegulatedIndustriesSuchAsHealthcareFinanceAndLegalServicesWithDataSecurityAndEncryptionForSensitiveDocumentsAndConfidentialInformationProtectionMechanismsBuiltIntoTheDocumentStorageAndTransmissionSystemsWithIntegrationCapabilitiesForEnterpriseContentManagementSystemsAndCloudStorageProvidersSupportingAPIsForAutomatedDocumentGenerationAndWorkflowAutomationWithCustomScriptingAndMacroFeaturesForAdvancedUsersAndDevelopersBuildingCustomSolutionsOnTopOfThePlatformWithExtensiveDocumentationAndCommunitySupportForThirdPartyExtensionsAndPluginsEnhancingTheCoreFunctionalityOfTheDocumentEditorWithSpecializedToolsForSpecificIndustriesOrUseCasesSuchAsScientificPublishingTechnicalManualsOrLegalContractsWithTemplateLibrariesAndStyleGuidesPreConfiguredForCommonDocumentTypesAndFormatsReducingSetupTimeAndEnsuringConsistencyAcrossOrganizationalDocumentsWithBrandAssetManagementFeaturesForLogosColorPalettesAndTypographySettingsAppliedGloballyAcrossAllDocumentsCreatedWithinThePlatformWithVersioningAndApprovalWorkflowsForDocumentLifecycleManagementSupportingElectronicSignaturesAndDigitalCertificatesForAuthenticationAndNonRepudiationPurposesInLegalAndBusinessTransactionsWithAuditLoggingAndReportingFeaturesForComplianceMonitoringAndRiskManagementInEnterpriseEnvironmentsWithScalableArchitectureSupportingLargeDocumentsWithThousandsOfPagesAndComplexLayoutsIncludingTablesChartsAndMultimediaElementsWithPerformanceOptimizationsForRealTimeRenderingAndEditingOfLargeDocumentsOnVariousHardwareConfigurationsFromMobileDevicesToHighEndWorkstationsWithOfflineCapabilitiesAndSyncFeaturesForWorkingInDisconnectedEnvironmentsOrAreasWithLimitedConnectivitySupportingProgressiveWebAppTechnologiesForNativeLikeExperiencesOnDesktopAndMobilePlatformsWithCrossPlatformCompatibilityAcrossMajorBrowsersAndOperatingSystemsEnsuringConsistentBehaviorAndAppearanceOfDocumentsRegardlessOfTheViewingEnvironmentWithAccessibilityFeaturesSuchAsScreenReaderSupportKeyboardNavigationHighContrastModesAndTextToSpeechFunctionalityForUsersWithDisabilitiesAdheringToInternationalAccessibilityStandardsAndRegulationsWithLocalizationSupportForMultipleLanguagesAndRegionalFormatsIncludingRightToLeftTextLayoutsForLanguagesSuchAsArabicAndHebrewWithCulturalAdaptationsForDateTimeNumberAndCurrencyFormatsBasedOnUserPreferencesOrDocumentRequirementsSupportingUnicodeCharacterSetsAndSpecializedTypographyFeaturesForNonLatinScriptsAndComplexTextLayoutsInLanguagesWithAdvancedTypographicRequirementsSuchAsThaiDevanagariOrCJKVCharactersWithFontEmbeddingAndSubsettingCapabilitiesForPreservingDocumentAppearanceAcrossDifferentSystemsAndDevicesEnsuringThatCustomFontsAreProperlyRenderedInExportedDocumentsRegardlessOfTheRecipientsFontLibraryWithAdvancedTypographyControlsForFineTuningTextAppearanceIncludingKerningTrackingLigaturesAndOpenTypeFeaturesSupportingProfessionalTypesettingRequirementsForPublishingIndustryStandardsWithColorManagementFeaturesForAccurateColorReproductionAcrossDifferentOutputDevicesAndMediaTypesIncludingPrintWebAndMobileDisplaysSupportingICCColorProfilesAndColorSpacesSuchAsSRGBAdobeRGBAndCMYKForPrepressWorkflowsWithImageEditingToolsIntegratedIntoTheDocumentEditorForBasicAdjustmentsSuchAsCroppingResizingColorCorrectionAndFiltersWithoutNeedingExternalSoftwareStreamliningTheDocumentCreationProcessByReducingContextSwitchingBetweenApplicationsWithCollaborativeEditingFeaturesAllowingMultipleUsersToWorkOnTheSameDocumentSimultaneouslyWithRealTimePresenceIndicatorsCursorTrackingAndChangeNotificationsEnhancingTeamProductivityAndReducingVersionConflictsCommonInTraditionalDocumentWorkflowsWithCommentingAndAnnotationToolsSupportingThreadedDiscussionsMentionsAndResolutionTrackingForEfficientReviewProcessesIntegratingWithProjectManagementAndCommunicationToolsSuchAsSlackMicrosoftTeamsOrJiraForSeamlessWorkflowIntegrationAcrossOrganizationalToolsWithTemplateVersioningAllowingUsersToTrackChangesToDocumentTemplatesOverTimeAndRevertToPreviousVersionsIfNeededMaintainingConsistencyWhileAllowingForIterativeImprovementsToTemplateDesignsBasedOnUserFeedbackOrChangingBusinessRequirementsWithAnalyticsAndInsightsFeaturesProvidingDataOnDocumentUsageReadershipEngagementAndCollaborationPatternsHelpingOrganizationsOptimizeTheirDocumentCreationProcessesAndImproveContentEffectivenessWithAI PoweredFeaturesSuchAsContentSuggestionsGrammarCheckingStyleRecommendationsAndAutomatedSummarizationAssistingUsersInCreatingHigherQualityDocumentsMoreEfficientlyLeveragingMachineLearningModelsTrainedOnLargeCorporaOfProfessionalDocumentsToProvideContextAwareAssistanceTailoredToSpecificDocumentTypesOrIndustriesWithDataPrivacyAndSecurityMeasuresEnsuringThatUserDataIsProtectedAccordingToIndustryBestPracticesAndRegulatoryRequirementsSuchAsGDPRHIPAAOrSOC2WithRegularSecurityAuditsAndPenetrationTestingToIdentifyAndAddressPotentialVulnerabilitiesProactivelyMaintainingUserTrustInThePlatformsSecurityPostureWithDisasterRecoveryAndBusinessContinuityFeaturesEnsuringThatUserDocumentsAreBackedUpSecurelyAndCanBeRestoredInCaseOfDataLossOrSystemFailuresProvidingServiceLevelAgreementsForUptimeAndSupportResponsivenessMeetingTheNeedsOfEnterpriseCustomersWithMissionCriticalDocumentWorkflowsSupportingAPIIntegrationsWithOtherBusinessSystemsSuchAsCRMsERPsOrCustomDatabasesEnablingAutomatedDocumentGenerationBasedOnDataFromTheseSystemsReducingManualDataEntryErrorsAndIncreasingOperationalEfficiencyWithWebhookSupportForEventDrivenWorkflowsTriggeringActionsInOtherSystemsWhenDocumentsAreCreatedModifiedOrPublishedCreatingConnectedDigitalExperiencesAcrossTheOrganizationsTechnologyStackSupportingCustomExtensionsAndPluginsDevelopedByThirdPartiesOrTheUserCommunityExpandingThePlatformsCapabilitiesBeyondItsCoreFeatureSetFosteringAnEcosystemOfSolutionsAroundTheDocumentEditorPlatformEncouragingInnovationAndSpecializationForDifferentUseCasesOrIndustriesWithMarketplaceFeaturesForDiscoveringSharingAndSellingExtensionsTemplatesAndOtherDigitalAssetsWithinTheUserCommunityCreatingEconomicOpportunitiesForDevelopersDesignersAndContentCreatorsBuildingOnThePlatformWithComprehensiveDeveloperToolsIncludingSDKsAPIDocumentationCodeSamplesAndTestingFrameworksLoweringTheBarrierToEntryForCreatingCustomIntegrationsOrExtensionsSupportingBothFrontendJavaScriptFrameworksSuchAsReactVueOrAngularAndBackendTechnologiesLikeNodeJSPythonJavaOrNetProvidingFlexibilityForIntegrationIntoDiverseTechnologyEnvironmentsFoundInModernOrganizationsWithSandboxedExecutionEnvironmentsForExtensionsEnsuringThatThirdPartyCodeCannotCompromiseTheSecurityOrStabilityOfTheCorePlatformProtectingUserDataWhileAllowingForCustomFunctionalityThroughCarefullyDesignedAPIsThatBalanceFlexibilityWithSecurityControlsSupportingMonetizationModelsForExtensionDevelopersIncludingOneTimePurchasesSubscriptionsOrUsageBasedPricingEnablingSustainableBusinessModelsAroundThePlatformsEcosystemFosteringLongTermGrowthAndInnovationThroughPartnershipsWithIndependentSoftwareVendorsSystemIntegratorsAndConsultingFirmsSpecializingInDocumentWorkflowSolutionsCreatingAThrivingPartnerNetworkThatExtendsThePlatformsReachIntoNewMarketsAndVerticalsThroughSpecializedExpertiseAndLocalPresenceInDifferentGeographicRegionsOrIndustrySectorsBuildingABroadCommunityOfUsersDevelopersPartnersContributorsTranslatorsTestersDocumentationWritersForumModeratorsAmbassadorsEvangelistsInfluencersAnalystsJournalistsBloggersPodcastersYouTubersStreamersEducatorsTrainersConsultantsAgenciesFreelancersEnterprisesSMBsNonprofitsGovernmentAgenciesAcademicInstitutionsResearchOrganizationsStandardsBodiesIndustryAssociationsOpenSourceProjectsCompetitorsComplementorsRegulatorsPolicyMakersInvestorsBoardMembersExecutivesManagersEmployeesContractorsInternsVolunteersCustomersClientsPatientsStudentsTeachersParentsChildrenSeniorsPersonsWithDisabilitiesMinorityGroupsMarginalizedCommunitiesDevelopingNationsRuralAreasUrbanCentersSuburbsCitiesStatesCountriesContinentsPlanetsGalaxiesUniversesMultiversesOmniversesDimensionsRealitiesTimelinesParallelWorldsAlternateHistoriesPossibleFuturesQuantumStatesSuperpositionsEntanglementsWormholesBlackHolesDarkMatterDarkEnergyCosmicBackgroundRadiationBigBangSingularitiesInflationaryPeriodsBubbleUniversesStringTheoryBranesMTheoryLoopQuantumGravityCausalSetsTwistorTheoryNoncommutativeGeometryInformationParadoxFirewallsEREPRHolographicPrincipleAdsCFTCorrespondenceCosmicCensorshipChronologyProtectionConjectureAnthropicPrincipleMultiverseSelectionQuantumImmortalitySimulationHypothesisBoltzmannBrainsPanspermiaDirectedPanspermiaFermiParadoxDrakeEquationGreatFilterKardashevScaleDysonSpheresMatrioshkaBrainsJupiterBrainsStellarEnginesShkadovThrustersAlcubierreDriveKrasnikovTubesWormholeStabilizationNegativeEnergyExoticMatterCasimirEffectQuantumVacuumPlasmaWakefieldAccelerationBeamedPowerSolarSailsLaserSailsMagneticSailsElectricSailsRamAugmentedInterstellarRocketExternalPulsedPlasmaPropulsionNuclearPulsePropulsionFusionRocketsAntimatterRocketsBussardRamjetVacuumEnergyPropulsionHawkingRadiationEnginesBlackHoleDrivesWhiteHoleDrivesWarpDrivesHyperdrivesJumpDrivesFoldDrivesSlideDrivesInertialessDrivesGravityDrivesTachyonDrivesChronitonDrivesSubspaceDrivesTranswarpDrivesQuantumSlipstreamTranswarpConduitsBorgTranswarpHubVothTranswarpNetworkIconianGatewaysBajoranWormholeBarzanWormholeSikarianSpatialTrajectorVaadwaurSubspaceCorridorsUnderspaceFluidicSpaceNullSpaceCocytusGravityWellsTractorBeamsRepulsorBeamsTetryonBeamsPhaserBeamsDisruptorBeamsPlasmaBeamsPolaronBeamsChronitonBeamsThoronBeamsMetreonBeamsVerteronBeamsTricobaltDevicesIsolyticWeaponsThalaronRadiationMetreonCascadeRedMatterOmegaMoleculeTransphasicTorpedoesChronitonTorpedoesSpatialTorpedoesQuantumTorpedoesPhotonTorpedoesPlasmaTorpedoesPolaronTorpedoesBiomimeticGelSilverBloodSpecies8472TheBorgTheDominionTheCardassiansTheRomulansTheKlingonsTheFerengiTheBreenTheTholiansTheGornTheOrionsTheNausicaansTheTalaxiansTheKazonTheVidiiansTheHirogenTheMalonTheKrenimTheVothTheSpecies10026TheThinkTankTheHazariTheNyriansTheSriviTheSon'aTheBa'kuTheXindiTheSphereBuildersTheTemporalColdWarTheMirrorUniverseTheKelvinTimelineThePrimeTimelineTheAlternateRealityTheMultiverseCrisisOnInfiniteEarthsFlashpointZeroHourInfiniteCrisisFinalCrisisConvergenceDarkNightsMetalDeathMetalInfiniteFrontierDarkCrisisShadowWarGenesisWarEternityWarSecretWarsCivilWarInfinityWarSecretInvasionHouseOfMCrisisOnXMenAgeOfApocalypseDaysOfFuturePastMessiahComplexSecondComingAvengersVsXMenSchismBattleOfTheAtomDeathOfXIvXMutantMassacreFallOfMutantsXTerminationXMenBlueXMenGoldXMenRedXMenBlackXMenGreenXMenWhiteXMenPurpleXMenOrangeXMenYellowXMenPinkXMenBrownXMenGrayXMenClearXMenFrostedXMenTintedXMenReflectiveXMenTranslucentXMenOpaqueXMenTransparentXMenLuminousXMenIridescentXMenPhosphorescentXMenFluorescentXMenIncandescentXMenCandescentXMenEffulgentXMenRefulgentXMenResplendentXMenSplendiferousXMenMagnificentXMenGloriousXMenMajesticXMenRegalXMenImperialXMenRoyalXMenAristocraticXMenPatricianXMenEquestrianXMenChivalricXMenGallantXMenValiantXMenIntrepidXMenDauntlessXMen}}}